export const GET_ALL_INVENTORY = "GET_ALL_INVENTORY";
export const GET_ALL_INVENTORY_SUCCESS = "GET_ALL_INVENTORY_SUCCESS";
export const GET_ALL_INVENTORY_FAIL = "GET_ALL_INVENTORY_FAIL";

export const EDIT_INVENTORY = "EDIT_INVENTORY";
export const EDIT_INVENTORY_SUCCESS = "EDIT_INVENTORY_SUCCESS";
export const EDIT_INVENTORY_FAIL = "EDIT_INVENTORY_FAIL";

export const DELETE_INVENTORY = "DELETE_INVENTORY";
export const DELETE_INVENTORY_SUCCESS = "DELETE_INVENTORY_SUCCESS";
export const DELETE_INVENTORY_FAIL = "DELETE_INVENTORY_FAIL";

export const ADD_INVENTORY = "ADD_INVENTORY";
export const ADD_INVENTORY_SUCCESS = "ADD_INVENTORY_SUCCESS";
export const ADD_INVENTORY_FAIL = "ADD_INVENTORY_FAIL";


